### ISSUE TITLE
Feedback android-auto-generate-dimension Problem

### ISSUE THREAD

**Issue by tcqq** [nvmanh/android-auto-generate-dimension#1]
Hello, thanks for your "android-auto-generate-dimension" library, I'm using your library, but I'm having a problem, first I copy the "autodimension.gradle" file to the "F:\AndroidStudioProjects\MyApplication" folder, 
![image](https://user-images.githubusercontent.com/10644057/37871440-74339966-3020-11e8-97c0-55490b557c81.png)
then I added (apply from: 'autodimension.gradle') to the "build.gradle" file,
![image](https://user-images.githubusercontent.com/10644057/37871450-a3ba87e4-3020-11e8-890e-ffac2660d965.png) then I run "gradlew createDimen" in the console, but no dimens.xml file is generated,
![image](https://user-images.githubusercontent.com/10644057/37871471-1ed6697a-3021-11e8-8379-187fcd8ab449.png)
what did i do wrong? How should I correct it? Thank you.

**Comment by nvmanh** [comment]
I use macosx and ubuntu, maybe this is problem with window os.
I will check it, thanks @tcqq

**Comment by tcqq** [comment]
Ok :)

**Comment by miq0717** [comment]
@nvmanh What's the solution for windows? I'm trying to use this from windows.
